### ISSUE TITLE
You can improve 'Startup' performance by disabling "BlackbirdSQL DDEX with SqlEditor Provider for Firebird" extension

### ISSUE THREAD

**Issue by MagicAndre1981** [BlackbirdSQL/Firebird-DDEX-SqlEditor#57]
In VS2022 17.10.3 I get [this warning at startup](https://learn.microsoft.com/en-us/visualstudio/ide/optimize-visual-studio-startup-time?view=vs-2022#startup-behavior):

`You can improve 'Startup' performance by disabling "BlackbirdSQL DDEX with SqlEditor Provider for Firebird" extension`

![image](https://github.com/BlackbirdSQL/Firebird-DDEX-SqlEditor/assets/8274816/48763ce7-7c32-4c25-bfa6-8813a9380fb7)

VS tells me that the extensions adds a 6s delay to startup.

**Comment by BlackbirdSQL** [comment]
I believe VS may be reporting this because BlackbirdSql goes back to the DbProviderFactory tables after everything is loaded to verify that other providers have not loaded late and been disabled by VS. 
This validation and reactivation routine is asynchronous and was introduced because the npgsql extension was not loading on the correct UIContexts in certain situations where the IDE had required an early load. As a result VS reported this validation as a BlackbirdSql startup delay.
We have since provided npgsql with a PR to fix this and they have implemented it. 
You shouldn't get this when v13.0.0.0 is released, which also performs optimistic trigger linkage to circumvent delays when Server Explorer nodes are expanded.

**Comment by BlackbirdSQL** [comment]
Version 13.0.0.0 is available. Let me know if you are still getting this message. I am leaving this issue open for a time until we're sure the issue is resolved.

**Comment by MagicAndre1981** [comment]
tahnsk for the update, I've installed it and the message is gone. I'll monitor it the next week and close the issue if I don't get it again.

**Comment by MagicAndre1981** [comment]
looks like the issue is gone and I can close it. Thanks for the fix.
