### ISSUE TITLE
Question: Why do you add GlobalBlackbirdPersistent = 3 to sln? 

### ISSUE THREAD

**Issue by MagicAndre1981** [BlackbirdSQL/Firebird-DDEX-SqlEditor#6]
Why do you add `GlobalBlackbirdPersistent = 3` to sln file? This makes useless changes to source version control.

**Comment by BlackbirdSQL** [comment]
Hi,
In the Readme this is explained. You can disable this feature in the `BlackbirdSql Server Tools` DDEX General options under EntityFramework settings.
___If it's an issue it can be changed___ to an opt-in rather than an opt-out option, ie. disabled by default. Let me know. It's 2 minutes to change.

#### Once-off Validation
It's a once off validation of a solution's app.config and edmx models to ensure correct configuration of these documents, so it will not update after an initial scan, if enabled.


#### The global's bit flags are as follows...
`// For Projects: has been validated as a valid project type (Once it's been validated it's always been
// validated)
// For Solutions: has been loaded and in a validation state if <see cref="G_Valid"/> is false else
// validated
const int G_Validated = 1;

// For Projects: Validated project is a valid executable C#/VB app (Project type). (Once [in]valid always
// [in]valid)
// For Solutions: Off: Solution has been loaded and is in a validation state. On: Validated
// (Only applicable if <see cref="G_Validated"/> is set)
const int G_Valid = 2;

// The app.config and all edmxs for a project have been scanned and configured if required. (Once
// successfully scanned always scanned)
const int G_Scanned = 4;

// The app.config has the client system.data/DbProviderFactory configured and is good to go. (Once
// successfully configured always configured)
const int G_DbProviderConfigured = 8;

// The app.config has the EntityFramework provider services and connection factory configured and is
// good to go. (Once successfully configured always configured)
const int G_EFConfigured = 16;

// Existing legacy edmx's have been updated and are good to go. (Once all successfully updated always
// updated)
const int G_EdmxsUpdated = 32;

//  If at any point in solution projects' validation there was a fail, this is set to true on the
//  solution and the solution Globals is reset to zero.
//  Validation on failed solution entities will resume the next time the solution is loaded.
const int G_ValidateFailed = 64;
`

**Comment by MagicAndre1981** [comment]
I changed the setting (restarted VS), but the value is always added, even to sln files where no DDEX/EF is used like Xamarin sln files. 

Please move such settings into a [Solution User Options (.suo) File](https://learn.microsoft.com/en-us/visualstudio/extensibility/internals/solution-user-options-dot-suo-file?view=vs-2022) , not in the real sln.

**Comment by BlackbirdSQL** [comment]
Okay I am getting the same result as you are even when I set persistence to false on the Debug page, which should prevent any persistence across sessions. The solution validation code was written a long time ago so a bug has definitely crept in. 
Also, CPS projects should be ignored even if validation is enabled, which includes Xamarin, but Microsoft has changed the internals several times without notice on updates, which has broken a number of extensions, and it may be the case here.
Moving the variable storage from DTE.Solution.Globals (.sln) to Package Options (.suo) is relatively straight forward.
I have never worked with project .user files so I'll need to do some reading, because those will also need to be moved from Project.Globals, which stores in the project.

**Comment by BlackbirdSQL** [comment]
This issue has been resolved in version [10.0.3.0](https://github.com/BlackbirdSQL/Firebird-DDEX-SqlEditor/releases/download/v10.0.3.0/BlackbirdSql.VisualStudio.Ddex.vsix).
The status variables are now held in the .suo and .user files.
Let me know if this is working for you so that I can close.

Regards.

**Comment by MagicAndre1981** [comment]
> This issue has been resolved in version [10.0.3.0](https://github.com/BlackbirdSQL/Firebird-DDEX-SqlEditor/releases/download/v10.0.3.0/BlackbirdSql.VisualStudio.Ddex.vsix). The status variables are now held in the .suo and .user files. 

works, thanks
