### ISSUE TITLE
System.ArgumentException: Illegal characters in path when using extension (v13.0.0.0)

### ISSUE THREAD

**Issue by The-MAZZTer** [BlackbirdSQL/Firebird-DDEX-SqlEditor#60]
This appears to only occur sometimes when executing a SELECT query or trying to open the table designer for a table. I don't know anything about Firebird so I can't say why it only happens sometimes or what string it is trying to process that contains non-path characters. I peeked at the source code here and I didn't see anything I recognized.

Scenario: I have been provided a Firebird database. I have installed Firebird 3 (the version that is used in production) and am trying to access the database through Visual Studio. I have been trying to use EF Core Scaffolding but it cannot process Numeric columns so I have been trying to see if I can modify the column data types using this extension (Flamerobin doesn't seem to be able to edit columns), however these errors are preventing me from doing much through Server Explorer.

Sample stack trace:

IDE::EXCEPTION: 12.56.26.734421: Parse :: BlackbirdSql.VisualStudio.Ddex\Ctl\TConnectionUIProperties.cs :: 160
[System.ArgumentException] Illegal characters in path..
TRACE: at System.IO.Path.CheckInvalidPathCharacters(String path, Boolean checkAdditional)
at System.IO.Path.GetExtension(String path)
at BlackbirdSql.RctManager.GetConnectionSourceImpl() in C:\Server\Dev\Projects2022\Blackbird\BlackbirdSql,Core\Root\RctManager.cs:line 686
at BlackbirdSql.VisualStudio.Ddex.Ctl.TAbstractConnectionProperties.get_ConnectionSource()
at BlackbirdSql.VisualStudio.Ddex.Ctl.TConnectionUIProperties.Parse(String connectionString)

Not sure what is going on here, but the "ActiveDocument" of a Dte object (not in this repo) is ultimately being queried and the file extension being pulled off of it.

If this is supposed to be looking at the file path of the active tab in Visual Studio (this is only a guess since I have no experience in writing VS extensions), the error is probably happening because the tab does not correspond to a saved file on disk (such as a table design tab, or an unsaved SQL query tab.)

If this is the case, I would suggest adding checks to see if the path of the active document is actually a valid path before trying to find its extension.

**Comment by BlackbirdSQL** [comment]
No it's simply trying to establish if the active document is a .settings document so that the appropriate behavior can be applied in connection dialogs, so the fix for this has been done and will be in the next release.

So not sure you'll be able to perform DDL operations in the designer because that's a Microsoft extension and BlackbirdSql simply serves as the provider. 

You can pull the create or modify DDL script of any database object in FlameRobin and then manually do your changes.

Alternatively you can create a .Net Framework project and use the edmx wizard to create an ADO.NET Entity Data Model. That should put you in the right direction on how to handle all the data types.

**Comment by BlackbirdSQL** [comment]
Release 13.1.0.1 is available for download. This issue has been resolved in this release.
