### ISSUE TITLE
System.Runtime.InteropServices.COMException] Error HRESULT E_FAIL has been returned from a call to a COM component. 

### ISSUE THREAD

**Issue by MagicAndre1981** [BlackbirdSQL/Firebird-DDEX-SqlEditor#75]
After last update I saw this in output window -> BlackbirdSql Pane while loading a CPP project without anything related to EF:

```
IDE::EXCEPTION: 05.12.01.289275:   AsyuiReindexEntityFrameworkAssemblies :: BlackbirdSql.Sys\Root\NativeDb.cs :: 248
	[System.Runtime.InteropServices.COMException] Error HRESULT E_FAIL has been returned from a call to a COM component. 
TRACE:    at VSLangProj.References.Find(String bstrIdentity)
   at BlackbirdSql.NativeDb.ReindexEntityFrameworkAssemblies(Project project) in C:\Server\Dev\Projects2022\Blackbird\BlackbirdSql.Sys\Root\NativeDb.cs:line 349
   at BlackbirdSql.NativeDb.<>c__DisplayClass88_0.<<AsyuiReindexEntityFrameworkAssemblies>b__0>d.MoveNext() in C:\Server\Dev\Projects2022\Blackbird\BlackbirdSql.Sys\Root\NativeDb.cs:line 244
```

**Comment by BlackbirdSQL** [comment]
Hmmm this is a strange one because this code should already have bombed at the previous `IsEditableProject()` statement which does that check. It looks like the optimizer is discarding the previous statement as redundant.

Either way this is a bug because that loop has to complete otherwise you're going to get **_Cannot cast Type A to Type B_** fails when there are Firebird assembly mismatches.

The fix is done. I'd really appreciate if you could check it out once it's been tested on my side and uploaded.

**Comment by BlackbirdSQL** [comment]
Release 14.5.0.2 has been uploaded and should address this issue. You can view the [Changelog here](https://github.com/BlackbirdSQL/Firebird-DDEX-SqlEditor/discussions/76).
If you could have a look and let me know, I'd appreciate it. Thanks.

**Comment by MagicAndre1981** [comment]
>  If you could have a look and let me know, I'd appreciate it. Thanks.

I still see it:

```
IDE::EXCEPTION: 02.29.10.775047:   AsyuiReindexEntityFrameworkAssemblies :: BlackbirdSql.Sys\Root\NativeDb.cs :: 248
	[System.Runtime.InteropServices.COMException] Error HRESULT E_FAIL has been returned from a call to a COM component. 
TRACE:    at VSLangProj.References.Find(String bstrIdentity)
   at BlackbirdSql.NativeDb.ReindexEntityFrameworkAssemblies(Project project) in C:\Server\Dev\Projects2022\Blackbird\BlackbirdSql.Sys\Root\NativeDb.cs:line 354
   at BlackbirdSql.NativeDb.<>c__DisplayClass88_0.<<AsyuiReindexEntityFrameworkAssemblies>b__0>d.MoveNext() in C:\Server\Dev\Projects2022\Blackbird\BlackbirdSql.Sys\Root\NativeDb.cs:line 244
```

**Comment by MagicAndre1981** [comment]
I tried to compile [zlib](https://github.com/madler/zlib) when I see this.

**Comment by BlackbirdSQL** [comment]
I'm making a hash of this. I've been looking at the latest source and had the wrong line number.
Visual Studio resets everything after a build so this exception is occurring on the AfterBuild event.
I am unable to replicate your issue but I can see where the problem is and put in the necessary conditionals.
The update is available as [Release 14.5.0.3](https://github.com/BlackbirdSQL/Firebird-DDEX-SqlEditor/discussions/77).
Please let me know.

**Comment by BlackbirdSQL** [comment]
I cannot replicate what you're getting but this is a timing issue within the IDE where properties like `Project.Properties` and `Project.References` are temporarily unavailable. It can even occur on an `AfterProjectLoaded` event, when a project should be ready. Below is the result I am getting on release 14.5.0.0. 
Release 14.5.0.3 includes a check for availability of the `Project.References` property whenever it is accessed, so I think this should be resolved.

![zlibbuild](https://github.com/user-attachments/assets/4b4930da-76aa-48c9-9f97-c2865848dab4)

**Comment by MagicAndre1981** [comment]
> Release 14.5.0.3 includes a check for availability of the `Project.References` property whenever it is accessed, so **I think this should be resolved.**

yes, this is solved now. Thanks 👍
